name: Build YOJ

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: Build YOJ - Unit Tests
    runs-on: ubuntu-latest

    env:
      MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn $MAVEN_ARGS verify
  integration-test:
    name: Build YOJ - YDB Repository Integration Tests [TableService]
    runs-on: ubuntu-latest

    env:
      MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn $MAVEN_ARGS -Plombok,integration-test -DargLine='-Dtech.ydb.yoj.repository.ydb.client.impl=table' -am -pl :yoj-repository-ydb-v2 verify
  integration-test-queryservice:
    name: Build YOJ - YDB Repository Integration Tests [QueryService]
    runs-on: ubuntu-latest

    env:
      MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn $MAVEN_ARGS -Plombok,integration-test -DargLine='-Dtech.ydb.yoj.repository.ydb.client.impl=query' -am -pl :yoj-repository-ydb-v2 verify
  integration-test-queryservice-unlimited:
    name: Build YOJ - YDB Repository Integration Tests [QueryService, unlimited rows]
    runs-on: ubuntu-latest

    env:
      MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn $MAVEN_ARGS -Plombok,integration-test -DargLine='-Dtech.ydb.yoj.repository.ydb.client.impl=query -Dtech.ydb.yoj.repository.ydb.client.resultRowsLimit=-1' -am -pl :yoj-repository-ydb-v2 verify
  javadoc-and-source:
    name: Validate JavaDoc
    runs-on: ubuntu-latest

    env:
      MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn $MAVEN_ARGS -Plombok,javadoc-and-source -DskipTests verify
